@extends('errors.layout')
@section('code', '404')
@section('icon', 'search_off')
@section('title', 'Halaman Tidak Ditemukan')
@section('message', 'Halaman yang kamu cari tidak ada atau sudah dipindahkan. Coba kembali ke beranda.')
